name: maps_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_map: ^8.1.1
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  latlong2: ^0.9.1
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  go_router: ^14.8.1
  flutter_localization: ^0.3.2
  logger: ^2.5.0
  geolocator: ^13.0.4
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  formz: ^0.8.0
  flutter_secure_storage: ^9.2.4
  internet_connection_checker_plus: ^2.7.1
  flutter_spinkit: ^5.2.1
  flutter_custom_clippers: ^2.1.0
  dio: ^5.8.0+1
  flutter_local_notifications: ^19.1.0
  flutter_background_service: ^5.1.0
  permission_handler: ^12.0.0+1
  http_interceptor: ^2.0.0
  flutter_expandable_fab: ^2.4.1
  lucide_icons: ^0.257.0
  flutter_foreground_task: ^9.1.0
  intl: ^0.19.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/
    - .env
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"
  image: "assets/logo.png"

  android_12:
    image: "assets/logo_android_12.png"
    color: "#ffffff"


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_bg.png"
